Final version (probablz with errors)

diff --git a/githooks/pre-commit b/githooks/pre-commit
--- a/githooks/pre-commit
+++ b/githooks/pre-commit
@@ -3,19 +3,28 @@ git stash -q --keep-index
 RESULT=$?
 
 files=$(git diff --name-only --cached | grep .py)
-pylint=$(pylint $files)
-f=$(flake8 $files)
+echo $files
+pylint $files
+pylint=$?
+flake8 $files
+flake=$?
+#echo $pylint
+#f=$(flake8 $files)
+#echo $f
 
 
 git stash pop -q
 if [ $RESULT -ne 0 ]; then
 echo "Unable to commit due to failing tests!"
+exit 1
 fi
 
 if [ $pylint -ne 0 ]; then
-echo "Unable to commit due to failing tests!"
+echo "Unable to commit due to failing pylint"
+exit 1
 fi
 
-if [ $f -ne 0 ]; then
-echo "Unable to commit due to failing tests!"
+if [ $flake -ne 0 ]; then
+echo "Unable to commit due to failing flake8!"
+exit 1
 fi
